### ISSUE TITLE
[timer] Something hapen

### ISSUE THREAD

**Issue by clammet** [clammet/pyBurlyBot#76]
```
2016-11-19 19:27:14-0600 [BurlyBot (TLSMemoryBIOProtocol),client] CheckNick
2016-11-19 19:27:14-0600 [-] Traceback (most recent call last):
2016-11-19 19:27:14-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
2016-11-19 19:27:14-0600 [-]     self.mainLoop()
2016-11-19 19:27:14-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-11-19 19:27:14-0600 [-]     self.runUntilCurrent()
2016-11-19 19:27:14-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/internet/base.py", line 797, in runUntilCurrent
2016-11-19 19:27:14-0600 [-]     f(*a, **kw)
2016-11-19 19:27:14-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/internet/threads.py", line 117, in _callFromThread
2016-11-19 19:27:14-0600 [-]     result = defer.maybeDeferred(f, *a, **kw)
2016-11-19 19:27:14-0600 [-] --- <exception caught here> ---
2016-11-19 19:27:14-0600 [-]   File "/home/bbm/opt/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
2016-11-19 19:27:14-0600 [-]     result = f(*args, **kw)
2016-11-19 19:27:14-0600 [-]   File "/home/bbm/pyBurlyBot/util/timer.py", line 57, in _addTimer
2016-11-19 19:27:14-0600 [-]     raise TimerExists("Timer (%s) already exists." % name)
2016-11-19 19:27:14-0600 [-] util.timer.TimerExists: Timer (alert_timer) already exists.
```

**Comment by gkistler** [comment]
Probably related to #74.  The alert module won't work quite correctly with reloads until that's fleshed out.

**Comment by clammet** [comment]
> This comment is authored by Fable 5

Resolved in 7feb934. alert.py now guards adds with `except TimerExists`, uses network-scoped timer names (`alert_timer:<network>`), and tears down via `Timers._delPrefix` in `unload()`. Residual (timer not re-armed after `.reload` until reconnect) is tracked as #74.
